import { UserCreationAttrs } from './users.model';

export const userInitialData: UserCreationAttrs[] = [
  {
    id: 1,
    email: 'admin@mail.com',
    name: 'Босс',
    password: '$2a$05$.U3EHC8wXoW4eSRjhqTJmebtDD8rgmEaAIsrtcOr9f/I75KCkMuJG',
    companyId: 1,
    confirmed: true,
    confirmedDate: new Date(),
    confirmedToken: null,
    adminToken: 'U3EHC8wXoW4eSRjhqTJmebtDD8rgm',
  },
  {
    id: 2,
    email: 'manager@mail.com',
    name: 'Начальника',
    password: '$2a$05$.U3EHC8wXoW4eSRjhqTJmebtDD8rgmEaAIsrtcOr9f/I75KCkMuJG',
    companyId: 1,
    confirmed: true,
    confirmedDate: new Date(),
    confirmedToken: null,
    adminToken: 'U3EHC8wXoW4jhqTJmebtDD8rgm',
  },
  {
    id: 3,
    email: 'worker@mail.com',
    name: 'Джамшут',
    password: '$2a$05$.U3EHC8wXoW4eSRjhqTJmebtDD8rgmEaAIsrtcOr9f/I75KCkMuJG',
    companyId: 1,
    confirmed: true,
    confirmedDate: new Date(),
    confirmedToken: null,
    adminToken: 'U3EHC8wXoW4eSRjhqTJbtDD8rgm',
  },
  {
    id: 4,
    email: 'worker1@mail.com',
    name: 'Равшан',
    password: '$2a$05$.U3EHC8wXoW4eSRjhqTJmebtDD8rgmEaAIsrtcOr9f/I75KCkMuJG',
    companyId: 1,
    confirmed: true,
    confirmedDate: new Date(),
    confirmedToken: null,
    adminToken: 'U3EHC8wXoW4eSRjhqTJmebtDD8rg',
  },
  {
    id: 5,
    email: 'admin2@mail.com',
    name: 'AdminOther',
    password: '$2a$05$.U3EHC8wXoW4eSRjhqTJmebtDD8rgmEaAIsrtcOr9f/I75KCkMuJG',
    companyId: 2,
    confirmed: true,
    confirmedDate: new Date(),
    confirmedToken: null,
    adminToken: 'U3EHC8wXoW4eSRjhqTJmebtDD8r',
  },
];
